"""Shared FastAPI dependencies: request identity and the anonymous quota gate.

Identity resolution order:

1. ``Authorization: Bearer <token>`` — a signed-in user.
2. ``X-Anon-Id: <uuid>`` — the per-browser anonymous id generated by the
   frontend (stored in localStorage); falls back to the client IP when the
   header is absent.

The identity ``label`` (``user:3`` / ``anon:<id>``) is what sessions and
knowledge-base documents record as their owner, which is how research is
isolated between users.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Optional

from fastapi import HTTPException, Request

from src.auth.service import AuthError, get_auth_service

_TOKEN_RE = re.compile(r"^[0-9a-f]{64}$")
_ANON_ID_RE = re.compile(r"^[A-Za-z0-9._-]{1,96}$")

__all__ = ["Identity", "extract_bearer_token", "get_identity", "consume_question_quota"]


@dataclass
class Identity:
    """Resolved caller identity used for ownership and quota decisions."""

    label: str
    """Ownership key written onto sessions/documents: ``user:3`` or ``anon:x``."""

    user: Optional[dict] = None
    """``{"id", "username", ...}`` when signed in, else None."""

    anon_id: Optional[str] = None
    """Anonymous tracker key (header value or ``ip-<host>`` fallback)."""

    token: str = ""
    """Raw bearer token (kept for logout)."""

    @property
    def is_anonymous(self) -> bool:
        return self.user is None


def extract_bearer_token(request: Request) -> str:
    """Return the bearer token when it looks like one of ours, else ``""``."""
    header = request.headers.get("authorization", "")
    if not header.lower().startswith("bearer "):
        return ""
    token = header[7:].strip().lower()
    return token if _TOKEN_RE.match(token) else ""


def _anonymous_id(request: Request) -> str:
    raw = (request.headers.get("x-anon-id") or "").strip()
    if raw and _ANON_ID_RE.match(raw):
        return raw
    host = request.client.host if request.client else "unknown"
    return f"ip-{host}"


async def get_identity(request: Request) -> Identity:
    """Resolve the caller to a signed-in user or an anonymous identity."""
    token = extract_bearer_token(request)
    if token:
        user = await get_auth_service().resolve_token(token)
        if user:
            return Identity(label=f"user:{user['id']}", user=user, token=token)
    anon_id = _anonymous_id(request)
    return Identity(label=f"anon:{anon_id}", anon_id=anon_id)


async def consume_question_quota(identity: Identity) -> Optional[int]:
    """Charge one question against the anonymous quota.

    Returns the remaining free-question count; ``None`` means "not tracked"
    (signed-in user, or the quota store is unavailable and the check fails
    open — an intentional graceful degradation for the demo).
    """
    if not identity.is_anonymous:
        return None
    try:
        return await get_auth_service().consume_question(identity.anon_id or "")
    except AuthError as exc:
        raise HTTPException(
            status_code=exc.status_code,
            detail={"code": exc.code, "message": exc.message},
        ) from exc
